import type {
  ReasoningInput,
  ReasoningOutput,
  ReasoningProvider,
} from '../contracts/core.js';

/**
 * G6-08 (Phase 2) — Controlled-stub reasoning provider.
 *
 * A production-safe stub provider that satisfies the {@link ReasoningProvider}
 * contract WITHOUT any external service dependencies. Used to exercise the
 * production-mode positive path end-to-end (Gateway → MissionService →
 * Orchestrator → Runtime → Verification → Artifact) in tests where real
 * ZAI/OpenAI/Anthropic providers are unavailable.
 *
 * Activation:
 *   GENESIS_REASONING_PROVIDER=stub
 *
 * The stub writes one deterministic artifact (`output.md`) and finishes. It
 * is NOT a real LLM — its output is fixed and predictable. The production
 * gateway must NOT silently fall back to this stub; it is only loaded when
 * explicitly requested via the env var above.
 *
 * Comparison to the dev-mode fallback (`buildDefaultReasoning()` in
 * MissionService): the dev-mode fallback is used ONLY when
 * `GENESIS_EXECUTION_MODE=development`. This stub provider is used ONLY
 * when `GENESIS_EXECUTION_MODE=production` AND
 * `GENESIS_REASONING_PROVIDER=stub`. The two are distinct paths — the
 * production path never silently substitutes dev fixtures.
 */

export interface StubReasoningOptions {
  /** File path the stub will write (default: 'output.md'). */
  readonly outputPath?: string;
  /** File content the stub will write (default: a fixed banner). */
  readonly outputContent?: string;
}

const DEFAULT_OUTPUT_PATH = 'output.md';
const DEFAULT_OUTPUT_CONTENT =
  '# Genesis stub-reasoning output\n\nGenerated by the controlled-stub reasoning provider.\n';

export class StubReasoningProvider implements ReasoningProvider {
  readonly name = 'controlled-stub-reasoning';
  private step = 0;
  private readonly outputPath: string;
  private readonly outputContent: string;

  constructor(opts: StubReasoningOptions = {}) {
    this.outputPath = opts.outputPath ?? DEFAULT_OUTPUT_PATH;
    this.outputContent = opts.outputContent ?? DEFAULT_OUTPUT_CONTENT;
  }

  async reason(_input: ReasoningInput): Promise<ReasoningOutput> {
    // G6-08 (Phase 5 lint fix): _input is intentionally unused — the stub
    // ignores the reasoning input and emits a fixed deterministic action.
    // Prefix with _ to signal intentional non-use to eslint.
    void _input;
    this.step += 1;
    if (this.step === 1) {
      return {
        text: JSON.stringify({
          action: 'write_file',
          path: this.outputPath,
          contents: this.outputContent,
        }),
      };
    }
    return {
      text: JSON.stringify({
        action: 'finish',
        summary: `wrote ${this.outputPath}`,
        artifacts: [this.outputPath],
      }),
    };
  }
}
